version: "3"

services:
  download-csv:
    build:
      context: docker/github-repos
      dockerfile: Dockerfile
    environment:
      LANGUAGE_OF_INTEREST: "python"
    image: "curation-dev-python-challenge-download-csv"
    stdin_open: true # docker run -i
    tty: true        # docker run -t